apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-service
  template:
    metadata:
      labels:
        app: iot-service
    spec:
      containers:
        - name: iot-service
          image: iot-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: DB_HOST
              value: mysql-db
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: Melisse123*
            - name: DB_NAME
              value: iotdb
            - name: DB_PORT
              value: "3306"
            - name: USER_SERVICE_URL
              value: http://user-service:3001
